# Generated by Django 4.2.2 on 2023-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
