# Generated by Django 4.2.2 on 2023-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0003_prioridad_tareas_asignado_a_tareas_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prioridad',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='prioridad',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, null=True),
        ),
    ]
