# Generated by Django 4.2.2 on 2023-07-09 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app7', '0004_remove_prioridad_nombre_remove_tareas_asignado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='asignado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app7.prioridad'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
